### PR TITLE
Fix error with empty array

### PR DESCRIPTION
**Pull request by Exelord**
Hi @HeroicEric,
This PR fixed an error related to empty arrays or null value.

### CODE REVIEW

**Comment by esbanarango** [comment]
Hello @Exelord could you rebase? I'll be happy to merge this.

**Comment by Exelord** [comment]
1 year later :D 
sure I will try

**Comment by Exelord** [comment]
Merge? :D

**Comment by esbanarango** [comment]
Thank you @Exelord

**Pull request merged**
